version: "3"
services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    command: sh -c "sleep 1; php /var/www/test.php"
    working_dir: /var/www
    volumes:
      - ./:/var/www

  redis:
    build:
      dockerfile: ./docker/redis/Dockerfile
      context: .
    ports:
      - 6379:6379