version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
    - "82:80"
    volumes:
    - ./sites:/etc/nginx/conf.d
    - ./app:/var/www
    - ./logs:/var/log/nginx
    depends_on:
    - php
  php:
    image: php:7.3-fpm
    volumes:
    - ./app:/var/www