version: '3'

networks:
    default:
        driver: bridge

services:
    nginx:        
        image: nginx:1.17.1
        ports:
            - "80:80"
        volumes:
            - ./src:/apps/otus
            - ./hosts:/etc/nginx/conf.d
            - ./sock:/var/run
        networks:
            - default
        links:
            - php
    php:
        build: ./images/php
        volumes:
            - ./src:/apps/otus
            - ./conf/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            - ./sock:/var/run
        networks:
            - default
        links:
            - composer
    composer:
        image: composer:1.8.6
        volumes:
            - ./src/:/app
        networks:
            - default
        command: composer install --ignore-platform-reqs

