version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build: ./images/php
    volumes:
      - ./www:/var/www