version: "3.5"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - "sockdrive:/var/run"
    ports:
      - "80:80"
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    volumes:
      - ./php.www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - "sockdrive:/var/run"

volumes:
  sockdrive: