version: '3.7'

services:
  nginx:
    image: nginx
    restart: on-failure
    build: ./Dockerfiles/nginx/.
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../src:/usr/share/nginx/html
    depends_on:
      - php
      - db

  php:
    image: php:7.3-fpm
    restart: on-failure
    build: ./Dockerfiles/php/.
    working_dir: /usr/share/nginx/html
    volumes:
      - ./../src:/usr/share/nginx/html
    ports:
      - 9000:9000
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./dump/cinemaDB.sql:/docker-entrypoint-initdb.d/cinemaDB.sql

