version: '3'

networks:
  default:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../src:/apps/otus
      - ./hosts:/etc/nginx/conf.d
      - ./sock:/var/run
    networks:
      - default
    links:
      - php
  php:
    build: ./images/php
    volumes:
      - ../src:/apps/otus
      - ./conf/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./sock:/var/run
    networks:
      - default
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:latest
    networks:
      - default

