version: '3'
services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www/public
      - ../src/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www/public
