version: '3'
services:
    nginx:
        build: Docker/nginx
        container_name: nginx
        volumes:
            - app-data:/var/www/html
            - sockets-data:/sockets
            - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80
        links:
            - php
            
    php:
        build: Docker/php
        image: php:hw6-2
        container_name: php
        volumes:
            - app-data:/var/www/html
            - sockets-data:/sockets
            - ./Docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
            
volumes:
    app-data:
        driver: local
    sockets-data:
        driver: local
