version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./html:/var/www/html
        ports:
            - 8000:80
        links:
            - php
            
    php:
        build: Docker/php
        image: php:hw6-2
        container_name: php
        volumes:
            - ./html:/var/www/html
