version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - php-fpm
  php-fpm:
    image: php:7-fpm
    container_name: php
    volumes:
      - ./code:/code